<a href="https://colab.research.google.com/github/divya374r1/Neural-Network-and-Deep-Learning/blob/main/Addition_of_two_random_numbers(2%2C3)(1_Numpy_2_Tensorflow).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#1.perform element-wise addition on two(2,3)tensors with random values using numpy

import numpy as np

# Create two (2,3) tensors with random values
A = np.random.rand(2, 3)
B = np.random.rand(2, 3)

# Element-wise addition
C = A + B

# Display results
print("Tensor A:\n", A)
print("\nTensor B:\n", B)
print("\nElement-wise Addition (A + B):\n", C)


Tensor A:
 [[0.28555935 0.99465486 0.25924518]
 [0.1356243  0.74033574 0.82655242]]

Tensor B:
 [[0.45168356 0.28887252 0.1720841 ]
 [0.42455416 0.60640334 0.51994872]]

Element-wise Addition (A + B):
 [[0.73724291 1.28352738 0.43132929]
 [0.56017846 1.34673908 1.34650114]]


In [2]:
#2.perform element-wise addition on two(2,3)tensors with random values using numpy

import tensorflow as tf

# Create two (2,3) tensors with random values
A = tf.random.uniform((2, 3))
B = tf.random.uniform((2, 3))

# Element-wise addition
C = tf.add(A, B)

# Display results
print("Tensor A:\n", A)
print("\nTensor B:\n", B)
print("\nElement-wise Addition (A + B):\n", C)


Tensor A:
 tf.Tensor(
[[0.95984375 0.71596336 0.37290204]
 [0.2704985  0.64965093 0.69698024]], shape=(2, 3), dtype=float32)

Tensor B:
 tf.Tensor(
[[0.5535873  0.13577092 0.19372165]
 [0.7360779  0.15930486 0.79950964]], shape=(2, 3), dtype=float32)

Element-wise Addition (A + B):
 tf.Tensor(
[[1.5134311 0.8517343 0.5666237]
 [1.0065764 0.8089558 1.4964899]], shape=(2, 3), dtype=float32)
