In [ ]:
#1.What is the syntax for creating a tensors
import torch
t = torch.tensor([1, 2, 3, 4])
print(t)

tensor([1, 2, 3, 4])


In [ ]:
#2.What are the different tensor operations
import torch
a = torch.tensor([1, 2, 3])
b = torch.tensor([4, 5, 6])
# Arithmetic operation (addition)
c = a + b
print("Tensor a:", a)
print("Tensor b:", b)
print("Addition result:", c)


Tensor a: tensor([1, 2, 3])
Tensor b: tensor([4, 5, 6])
Addition result: tensor([5, 7, 9])


In [ ]:
#3. Create a 2*3 tensor filled with zeros and another filled with ones
import torch
# Create 2x3 tensor of zeros
zeros_tensor = torch.zeros(2, 3)
# Create 2x3 tensor of ones
ones_tensor = torch.ones(2, 3)
print("Tensor of Zeros:")
print(zeros_tensor)
print("\nTensor of Ones:")
print(ones_tensor)


Tensor of Zeros:
tensor([[0., 0., 0.],
        [0., 0., 0.]])

Tensor of Ones:
tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [ ]:
#4.Convert a python list [[1,2,3],[4,5,6]] into a tensor and print its shape and data type
import torch
# Python list
lst = [[1, 2, 3], [4, 5, 6]]
# Convert list to tensor
t = torch.tensor(lst)
print("Tensor:")
print(t)
print("Shape of tensor:", t.shape)
print("Data type of tensor:", t.dtype)


Tensor:
tensor([[1, 2, 3],
        [4, 5, 6]])
Shape of tensor: torch.Size([2, 3])
Data type of tensor: torch.int64


In [ ]:
#5.Reshape a tensor of size 12 into shape (3,4)
import torch
# Create a tensor with 12 elements
t = torch.arange(12)
print("Original tensor:")
print(t)
# Reshape into (3,4)
r = t.reshape(3, 4)
print("\nReshaped tensor (3x4):")
print(r)


Original tensor:
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

Reshaped tensor (3x4):
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])


In [ ]:
#6.Find the rank(number of dimensions)of a given tensor.
import torch
# Create a 3D tensor
t = torch.randn(2, 3, 4)
print("Tensor:")
print(t)
# Find rank (number of dimensions)
print("\nRank (number of dimensions) of tensor:", t.ndim)


Tensor:
tensor([[[ 0.9915,  0.2164,  0.3283,  0.7133],
         [-0.1797, -0.4229, -1.2430, -0.2604],
         [ 0.3084, -1.6526,  0.0547,  1.1276]],

        [[ 0.8747, -0.0429,  1.9392, -0.1618],
         [-0.7340,  0.4123, -0.7855, -1.0786],
         [-0.5314,  0.4983, -2.0729, -1.3141]]])

Rank (number of dimensions) of tensor: 3


In [ ]:
#7.Extract the second row and third column from a 2D tensor.
import torch
# Create a 2D tensor
t = torch.tensor([[1, 2, 3],
                  [4, 5, 6]])
print("Tensor:")
print(t)
# Extract second row and third column element
element = t[1, 2]
print("\nElement at second row and third column:", element)


Tensor:
tensor([[1, 2, 3],
        [4, 5, 6]])

Element at second row and third column: tensor(6)


In [ ]:
#8.Compute matrix multiplication between tensors of shape(3,4) and (4,2)
import torch
# Create a (3,4) tensor
A = torch.ones(3, 4)
# Create a (4,2) tensor
B = torch.ones(4, 2)
print("Tensor A:")
print(A)
print("\nTensor B:")
print(B)
# Matrix multiplication
C = torch.matmul(A, B)
print("\nResult of matrix multiplication:")
print(C)


Tensor A:
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

Tensor B:
tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]])

Result of matrix multiplication:
tensor([[4., 4.],
        [4., 4.],
        [4., 4.]])


In [ ]:
#9.Find the transpose of a 3D tensor.
import torch
# Create a 3D tensor of shape (2, 3, 4)
t = torch.tensor([[[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12]],

                  [[13, 14, 15, 16],
                   [17, 18, 19, 20],
                   [21, 22, 23, 24]]])

print("Original tensor shape:", t.shape)
print("Original tensor:")
print(t)
# Transpose the tensor by changing dimension order
tr = t.permute(2, 1, 0)
print("\nTransposed tensor shape:", tr.shape)
print("Transposed tensor:")
print(tr)


Original tensor shape: torch.Size([2, 3, 4])
Original tensor:
tensor([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],

        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]])

Transposed tensor shape: torch.Size([4, 3, 2])
Transposed tensor:
tensor([[[ 1, 13],
         [ 5, 17],
         [ 9, 21]],

        [[ 2, 14],
         [ 6, 18],
         [10, 22]],

        [[ 3, 15],
         [ 7, 19],
         [11, 23]],

        [[ 4, 16],
         [ 8, 20],
         [12, 24]]])


In [ ]:
#10.Implement softmax using tensor operations (no built-in function).
import torch
# Input tensor
x = torch.tensor([1.0, 2.0, 3.0])
print("Input tensor:", x)
# Step 1: Exponentiate the tensor
exp_x = torch.exp(x)
# Step 2: Divide by sum of exponentials
softmax = exp_x / exp_x.sum()
print("Softmax output:", softmax)


Input tensor: tensor([1., 2., 3.])
Softmax output: tensor([0.0900, 0.2447, 0.6652])


In [1]:
#11.Normalize a tensor so that values lie between 0 and 1.
import torch
# Create a tensor
x = torch.tensor([2.0, 4.0, 6.0])
print("Original tensor:", x)
# Normalize between 0 and 1
normalized = (x - x.min()) / (x.max() - x.min())
print("Normalized tensor:", normalized)


Original tensor: tensor([2., 4., 6.])
Normalized tensor: tensor([0.0000, 0.5000, 1.0000])


In [2]:
#12.Write code to compute gradients of a tensor operation(PyTorch).
import torch
# Create a tensor with gradient tracking enabled
x = torch.tensor(2.0, requires_grad=True)
# Perform an operation
y = x**2 + 3*x
print("Value of y:", y)
# Compute gradient
y.backward()
# Print gradient of y with respect to x
print("Gradient dy/dx:", x.grad)


Value of y: tensor(10., grad_fn=<AddBackward0>)
Gradient dy/dx: tensor(7.)


In [3]:
#13.Convert an image from(H,W,C) to (C,H,W)
import torch
# Create an image tensor of shape (H, W, C) = (2, 3, 3)
img = torch.tensor([[[1, 2, 3],
                     [4, 5, 6],
                     [7, 8, 9]],

                    [[10, 11, 12],
                     [13, 14, 15],
                     [16, 17, 18]]])

print("Original image tensor shape (H, W, C):", img.shape)
print("Original image tensor:")
print(img)

# Convert to (C, H, W)
img_chw = img.permute(2, 0, 1)

print("\nConverted image tensor shape (C, H, W):", img_chw.shape)
print("Converted image tensor:")
print(img_chw)


Original image tensor shape (H, W, C): torch.Size([2, 3, 3])
Original image tensor:
tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],

        [[10, 11, 12],
         [13, 14, 15],
         [16, 17, 18]]])

Converted image tensor shape (C, H, W): torch.Size([3, 2, 3])
Converted image tensor:
tensor([[[ 1,  4,  7],
         [10, 13, 16]],

        [[ 2,  5,  8],
         [11, 14, 17]],

        [[ 3,  6,  9],
         [12, 15, 18]]])


In [4]:
#14.Mask elements in a tensor based on a condition.
import torch
# Create a tensor
x = torch.tensor([1, -2, 3, -4, 5])
print("Original tensor:", x)
# Mask elements greater than 0
masked = x[x > 0]
print("Masked tensor (values > 0):", masked)


Original tensor: tensor([ 1, -2,  3, -4,  5])
Masked tensor (values > 0): tensor([1, 3, 5])


In [5]:
#15.Difference between view,reshape,and transpose in tensors.
import torch
# Create a tensor
x = torch.tensor([[1, 2, 3],
                  [4, 5, 6]])
print("Original tensor:")
print(x)
# view()
v = x.view(3, 2)
print("\nUsing view(3,2):")
print(v)
# reshape()
r = x.reshape(3, 2)
print("\nUsing reshape(3,2):")
print(r)
# transpose()
t = x.transpose(0, 1)
print("\nUsing transpose(0,1):")
print(t)


Original tensor:
tensor([[1, 2, 3],
        [4, 5, 6]])

Using view(3,2):
tensor([[1, 2],
        [3, 4],
        [5, 6]])

Using reshape(3,2):
tensor([[1, 2],
        [3, 4],
        [5, 6]])

Using transpose(0,1):
tensor([[1, 4],
        [2, 5],
        [3, 6]])


In [6]:
#16.What is contiguous memory in tensor operations?
import torch
# Create a tensor
x = torch.tensor([[1, 2, 3],
                  [4, 5, 6]])
print("Original tensor:")
print(x)
print("Is contiguous:", x.is_contiguous())
# Transpose the tensor
y = x.transpose(0, 1)
print("\nTransposed tensor:")
print(y)
print("Is contiguous:", y.is_contiguous())
# Make it contiguous
z = y.contiguous()
print("\nAfter making contiguous:")
print(z)
print("Is contiguous:", z.is_contiguous())


Original tensor:
tensor([[1, 2, 3],
        [4, 5, 6]])
Is contiguous: True

Transposed tensor:
tensor([[1, 4],
        [2, 5],
        [3, 6]])
Is contiguous: False

After making contiguous:
tensor([[1, 4],
        [2, 5],
        [3, 6]])
Is contiguous: True


In [7]:
#17.Why is broadcasting efficient?
import torch
# Create tensors of different shapes
a = torch.tensor([[1, 2, 3],
                  [4, 5, 6]])
b = torch.tensor([10, 20, 30])
print("Tensor a:")
print(a)
print("\nTensor b:")
print(b)
# Broadcasting happens here
c = a + b
print("\nResult after broadcasting (a + b):")
print(c)


Tensor a:
tensor([[1, 2, 3],
        [4, 5, 6]])

Tensor b:
tensor([10, 20, 30])

Result after broadcasting (a + b):
tensor([[11, 22, 33],
        [14, 25, 36]])


In [8]:
#18.Explain tensor vs matrix vs vector with examples.
import torch
# Vector (1D tensor)
vector = torch.tensor([1, 2, 3])
print("Vector:")
print(vector)
print("Vector shape:", vector.shape)
# Matrix (2D tensor)
matrix = torch.tensor([[1, 2, 3],
                       [4, 5, 6]])
print("\nMatrix:")
print(matrix)
print("Matrix shape:", matrix.shape)

# Tensor (3D tensor)
tensor3d = torch.tensor([[[1, 2, 3],
                           [4, 5, 6]],

                          [[7, 8, 9],
                           [10, 11, 12]]])
print("\nTensor (3D):")
print(tensor3d)
print("Tensor shape:", tensor3d.shape)


Vector:
tensor([1, 2, 3])
Vector shape: torch.Size([3])

Matrix:
tensor([[1, 2, 3],
        [4, 5, 6]])
Matrix shape: torch.Size([2, 3])

Tensor (3D):
tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]])
Tensor shape: torch.Size([2, 2, 3])


In [9]:
#19.How do tensor operations enable GPU acceleration?
import torch
# Check if GPU is available
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Device being used:", device)
# Create tensors and move to GPU (if available)
a = torch.tensor([1.0, 2.0, 3.0]).to(device)
b = torch.tensor([4.0, 5.0, 6.0]).to(device)

# Perform tensor operation
c = a + b

print("Result of tensor addition:", c)


Device being used: cpu
Result of tensor addition: tensor([5., 7., 9.])


In [10]:
#20.Implement cosine similarity using tensor operations
import torch
# Create two vectors
a = torch.tensor([1.0, 2.0, 3.0])
b = torch.tensor([4.0, 5.0, 6.0])
print("Vector A:", a)
print("Vector B:", b)
# Dot product
dot_product = torch.sum(a * b)
# Magnitudes
norm_a = torch.sqrt(torch.sum(a * a))
norm_b = torch.sqrt(torch.sum(b * b))
# Cosine similarity
cosine_similarity = dot_product / (norm_a * norm_b)

print("Cosine Similarity:", cosine_similarity)


Vector A: tensor([1., 2., 3.])
Vector B: tensor([4., 5., 6.])
Cosine Similarity: tensor(0.9746)
